import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import {
  ArrowRight,
  ArrowLeft,
  Database,
  HardDrive,
  ShieldCheck,
  Server,
  KeyRound,
  Download,
  Check,
  Terminal,
  Loader2,
  Copy,
  Plus,
  Trash2,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Separator } from "@/components/ui/separator";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";

const API_BASE = (import.meta.env.VITE_API_URL as string | undefined) || "/api";

interface WizardState {
  // Server users
  logUser: string;
  dbUser: string;
  dbPassword: string;
  adminEmail: string;
  // Storage / backup
  backupPath: string;
  backupCron: string;
  // Web
  hostname: string;
  serverIp: string;
  enableHttps: boolean;
  certPath: string;
  // Authentik / SSO
  installAuthentik: boolean;
  authentikUrl: string;
  authentikRealm: string;
  oidcClientId: string;
  oidcClientSecret: string;
  ssoGoogle: boolean;
  ssoMicrosoft: boolean;
  ssoSaml: boolean;
  ssoOidc: boolean;
  ssoPassword: boolean;
  authRequired: boolean;
}

const DEFAULT_STATE: WizardState = {
  logUser: "logsrv",
  dbUser: "dashboard",
  dbPassword: "",
  adminEmail: "",
  backupPath: "/var/backups/dashboard",
  backupCron: "0 3 * * *",
  hostname: "dashboard.local",
  serverIp: "0.0.0.0",
  enableHttps: true,
  certPath: "./certs",
  installAuthentik: true,
  authentikUrl: "https://auth.dashboard.local",
  authentikRealm: "dashboard",
  oidcClientId: "dashboard",
  oidcClientSecret: "",
  ssoGoogle: true,
  ssoMicrosoft: true,
  ssoSaml: true,
  ssoOidc: true,
  ssoPassword: true,
  authRequired: true,
};

const STEPS = [
  { id: "users", label: "User", icon: Server },
  { id: "db", label: "Datenbank", icon: Database },
  { id: "backup", label: "Backup & Cron", icon: HardDrive },
  { id: "web", label: "Web / TLS", icon: ShieldCheck },
  { id: "ssh", label: "SSH-Targets", icon: Terminal },
  { id: "sso", label: "SSO (Authentik)", icon: KeyRound },
  { id: "review", label: "Übersicht", icon: Check },
] as const;

function buildEnvFile(s: WizardState): string {
  const issuer = `${s.authentikUrl.replace(/\/$/, "")}/application/o/${s.oidcClientId}/`;
  return `# Generated by Dashboard Setup Wizard
# --- Server users ---
LOG_SRV_USER=${s.logUser}
DB_USER=${s.dbUser}
DB_PASSWORD=${s.dbPassword}
ADMIN_EMAIL=${s.adminEmail}

# --- Backup ---
BACKUP_PATH=${s.backupPath}
BACKUP_CRON=${s.backupCron}

# --- Web ---
SERVER_IP=${s.serverIp}
HOSTNAME=${s.hostname}
ENABLE_HTTPS=${s.enableHttps}
CERT_PATH=${s.certPath}

# --- SSO / Authentik ---
# INSTALL_AUTHENTIK=true: Authentik wird im Compose mit-installiert.
# false: bestehende Authentik-Instanz unter AUTHENTIK_URL wird genutzt.
INSTALL_AUTHENTIK=${s.installAuthentik}
AUTHENTIK_URL=${s.authentikUrl}
AUTHENTIK_REALM=${s.authentikRealm}
OIDC_CLIENT_ID=${s.oidcClientId}
OIDC_CLIENT_SECRET=${s.oidcClientSecret}

# --- Frontend (Vite) ---
VITE_AUTH_REQUIRED=${s.authRequired}
VITE_OIDC_AUTHORITY=${issuer}
VITE_OIDC_CLIENT_ID=${s.oidcClientId}
VITE_OIDC_REDIRECT_URI=${s.enableHttps ? "https" : "http"}://${s.hostname}/auth/callback
VITE_OIDC_POST_LOGOUT_URI=${s.enableHttps ? "https" : "http"}://${s.hostname}/login
VITE_SSO_GOOGLE_ENABLED=${s.ssoGoogle}
VITE_SSO_MICROSOFT_ENABLED=${s.ssoMicrosoft}
VITE_SSO_SAML_ENABLED=${s.ssoSaml}
VITE_SSO_OIDC_ENABLED=${s.ssoOidc}
VITE_SSO_PASSWORD_ENABLED=${s.ssoPassword}
`;
}

export default function SetupWizard() {
  const navigate = useNavigate();
  const [step, setStep] = useState(0);
  const [state, setState] = useState<WizardState>(DEFAULT_STATE);

  const update = <K extends keyof WizardState>(key: K, value: WizardState[K]) =>
    setState((s) => ({ ...s, [key]: value }));

  const envFile = useMemo(() => buildEnvFile(state), [state]);

  const downloadEnv = () => {
    const blob = new Blob([envFile], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = ".env";
    a.click();
    URL.revokeObjectURL(url);
    toast.success(".env heruntergeladen");
  };

  const next = () => setStep((s) => Math.min(STEPS.length - 1, s + 1));
  const prev = () => setStep((s) => Math.max(0, s - 1));

  const Current = STEPS[step];

  return (
    <div className="mx-auto max-w-4xl space-y-6 p-4 md:p-8">
      <header className="space-y-2">
        <h1 className="text-2xl font-semibold tracking-tight">Setup-Wizard</h1>
        <p className="text-sm text-muted-foreground">
          Erzeugt eine <code className="rounded bg-muted px-1">.env</code> für das
          Docker-Setup (Debian 12/13 oder Windows Docker Desktop). Die Werte
          werden von <code className="rounded bg-muted px-1">install.sh</code>
          und <code className="rounded bg-muted px-1">docker-compose.yml</code>
          gelesen.
        </p>
      </header>

      {/* Stepper */}
      <ol className="flex flex-wrap items-center gap-2 text-sm">
        {STEPS.map((s, i) => {
          const Icon = s.icon;
          const active = i === step;
          const done = i < step;
          return (
            <li key={s.id} className="flex items-center gap-2">
              <button
                onClick={() => setStep(i)}
                className={`flex items-center gap-2 rounded-full border px-3 py-1.5 transition ${
                  active
                    ? "border-primary bg-primary text-primary-foreground"
                    : done
                    ? "border-primary/40 bg-primary/10 text-primary"
                    : "border-border bg-card text-muted-foreground"
                }`}
              >
                <Icon className="h-3.5 w-3.5" />
                {s.label}
              </button>
              {i < STEPS.length - 1 && <ArrowRight className="h-3 w-3 text-muted-foreground" />}
            </li>
          );
        })}
      </ol>

      <section className="rounded-2xl border border-border bg-card p-6 shadow-sm">
        <h2 className="mb-4 flex items-center gap-2 text-lg font-medium">
          <Current.icon className="h-5 w-5 text-primary" />
          {Current.label}
        </h2>

        {Current.id === "users" && (
          <div className="grid gap-4 md:grid-cols-2">
            <Field label="Log-Server User (Linux)" value={state.logUser} onChange={(v) => update("logUser", v)} hint="System-User unter dem der Log-Collector läuft" />
            <Field label="Admin Email" value={state.adminEmail} onChange={(v) => update("adminEmail", v)} hint="Initialer Dashboard-Admin (wird in Authentik angelegt)" />
          </div>
        )}

        {Current.id === "db" && (
          <div className="grid gap-4 md:grid-cols-2">
            <Field label="Datenbank-User" value={state.dbUser} onChange={(v) => update("dbUser", v)} />
            <Field label="Datenbank-Passwort" value={state.dbPassword} onChange={(v) => update("dbPassword", v)} type="password" hint="Wird in das Postgres-Image als POSTGRES_PASSWORD übergeben" />
          </div>
        )}

        {Current.id === "backup" && (
          <div className="grid gap-4 md:grid-cols-2">
            <Field label="Backup-Verzeichnis" value={state.backupPath} onChange={(v) => update("backupPath", v)} hint="Volume für DB-Dumps und Log-Snapshots" />
            <Field label="Cron-Schedule" value={state.backupCron} onChange={(v) => update("backupCron", v)} hint="Standard 03:00 Uhr täglich" />
            <p className="md:col-span-2 text-xs text-muted-foreground">
              <code>install.sh</code> legt einen Cron-Eintrag im Backup-Container
              an, der täglich <code>pg_dump</code> + <code>tar</code> der Logs
              ausführt.
            </p>
          </div>
        )}

        {Current.id === "web" && (
          <div className="grid gap-4 md:grid-cols-2">
            <Field label="Server IP-Adresse" value={state.serverIp} onChange={(v) => update("serverIp", v)} hint="IP, an die der Reverse-Proxy bindet. 0.0.0.0 = alle Interfaces. install.sh erkennt vorhandene IPs automatisch." />
            <Field label="Hostname" value={state.hostname} onChange={(v) => update("hostname", v)} hint="z.B. dashboard.example.com" />
            <Toggle label="HTTPS aktivieren" checked={state.enableHttps} onChange={(v) => update("enableHttps", v)} hint="HTTP bleibt parallel auf Port 80 verfügbar" />
            <Field label="Zertifikats-Verzeichnis" value={state.certPath} onChange={(v) => update("certPath", v)} hint="Lege hier deine Let's-Encrypt fullchain.pem + privkey.pem ab" />
          </div>
        )}

        {Current.id === "ssh" && <SshWizardStep />}

        {Current.id === "sso" && (
          <div className="grid gap-4 md:grid-cols-2">
            <div className="md:col-span-2">
              <Toggle
                label="Authentik im Compose-Stack mit-installieren"
                checked={state.installAuthentik}
                onChange={(v) => update("installAuthentik", v)}
                hint="Aktiv: Authentik-Server, -Worker, -DB & -Redis werden lokal gestartet (URL: https://<host>/auth/). Aus: bestehende Authentik-Instanz unter der unten angegebenen URL wird genutzt."
              />
            </div>
            <Field
              label="Authentik URL"
              value={state.authentikUrl}
              onChange={(v) => update("authentikUrl", v)}
              hint={state.installAuthentik
                ? "Wird bei der Installation auf https://<HOSTNAME>/auth/ gesetzt."
                : "Basis-URL deiner bestehenden Authentik-Instanz (z. B. https://auth.example.com)."}
            />
            <Field label="Authentik Realm / Slug" value={state.authentikRealm} onChange={(v) => update("authentikRealm", v)} />
            <Field label="OIDC Client-ID" value={state.oidcClientId} onChange={(v) => update("oidcClientId", v)} />
            <Field label="OIDC Client-Secret" value={state.oidcClientSecret} onChange={(v) => update("oidcClientSecret", v)} type="password" hint="Aus Authentik → Provider → Dashboard kopieren" />

            <div className="md:col-span-2 mt-2 space-y-3">
              <Separator />
              <h3 className="text-sm font-medium">Aktive Login-Methoden</h3>
              <div className="grid gap-3 sm:grid-cols-2">
                <Toggle label="Google" checked={state.ssoGoogle} onChange={(v) => update("ssoGoogle", v)} />
                <Toggle label="Microsoft / Entra" checked={state.ssoMicrosoft} onChange={(v) => update("ssoMicrosoft", v)} />
                <Toggle label="SAML SSO" checked={state.ssoSaml} onChange={(v) => update("ssoSaml", v)} />
                <Toggle label="Generic OIDC" checked={state.ssoOidc} onChange={(v) => update("ssoOidc", v)} />
                <Toggle label="Email + Passwort (lokal)" checked={state.ssoPassword} onChange={(v) => update("ssoPassword", v)} hint="Lokales Authentik-Konto via username/password" />
                <Toggle label="Auth-Wall erzwingen" checked={state.authRequired} onChange={(v) => update("authRequired", v)} hint="Aktiv: Dashboard nur nach Login zugänglich, leitet auf /login um. Aus: freier Zugriff (Preview-Modus)." />
              </div>
              <p className="text-xs text-muted-foreground">
                Google / Microsoft / SAML werden als <strong>Federated Sources</strong>{" "}
                in Authentik konfiguriert. Die Buttons hier blenden sie nur in
                der Login-UI ein/aus. Username + Passwort funktioniert direkt
                gegen die lokale Authentik-Userdatenbank.
              </p>
            </div>
          </div>
        )}

        {Current.id === "review" && (
          <div className="space-y-4">
            <p className="text-sm text-muted-foreground">
              Lade die generierte <code>.env</code> herunter, lege sie neben
              <code> docker-compose.yml</code> und führe <code>./install.sh</code>{" "}
              aus (Linux) bzw. <code>docker compose up -d</code> (Windows).
            </p>
            <Textarea readOnly value={envFile} className="h-72 font-mono text-xs" />
            <div className="flex gap-2">
              <Button onClick={downloadEnv} className="gap-2">
                <Download className="h-4 w-4" /> .env herunterladen
              </Button>
              <Button variant="outline" onClick={() => navigate("/")}>Zum Dashboard</Button>
            </div>
          </div>
        )}
      </section>

      <div className="flex justify-between">
        <Button variant="outline" onClick={prev} disabled={step === 0} className="gap-2">
          <ArrowLeft className="h-4 w-4" /> Zurück
        </Button>
        <Button onClick={next} disabled={step === STEPS.length - 1} className="gap-2">
          Weiter <ArrowRight className="h-4 w-4" />
        </Button>
      </div>
    </div>
  );
}

function Field({
  label,
  value,
  onChange,
  hint,
  type = "text",
}: {
  label: string;
  value: string;
  onChange: (v: string) => void;
  hint?: string;
  type?: string;
}) {
  return (
    <div className="space-y-1">
      <Label>{label}</Label>
      <Input type={type} value={value} onChange={(e) => onChange(e.target.value)} />
      {hint && <p className="text-xs text-muted-foreground">{hint}</p>}
    </div>
  );
}

function Toggle({
  label,
  checked,
  onChange,
  hint,
}: {
  label: string;
  checked: boolean;
  onChange: (v: boolean) => void;
  hint?: string;
}) {
  return (
    <div className="flex items-start gap-3 rounded-md border border-border bg-background p-3">
      <Switch checked={checked} onCheckedChange={onChange} />
      <div className="space-y-0.5">
        <Label className="cursor-pointer">{label}</Label>
        {hint && <p className="text-xs text-muted-foreground">{hint}</p>}
      </div>
    </div>
  );
}

// ── SSH Wizard Step ─────────────────────────────────────────
interface SshTarget {
  id: string;
  label: string;
  host: string;
  user: string;
  port: number;
  result?: {
    ok: boolean;
    latency_ms?: number;
    stdout?: string;
    stderr?: string;
    hint?: string;
    error?: string;
  };
  testing?: boolean;
}

const DEFAULT_TARGETS: SshTarget[] = [
  { id: "opnsense", label: "OPNsense", host: "", user: "root", port: 22 },
  { id: "mailcow", label: "Mailcow Host", host: "", user: "root", port: 22 },
];

function SshWizardStep() {
  const [pubkey, setPubkey] = useState<string>("");
  const [pubkeyExists, setPubkeyExists] = useState<boolean | null>(null);
  const [keyPath, setKeyPath] = useState<string>("");
  const [generating, setGenerating] = useState(false);
  const [comment, setComment] = useState("dashboard@logsrv");
  const [targets, setTargets] = useState<SshTarget[]>(() => {
    try {
      const raw = localStorage.getItem("setup.sshTargets");
      if (raw) return JSON.parse(raw);
    } catch {}
    return DEFAULT_TARGETS;
  });

  useEffect(() => {
    fetch(`${API_BASE}/setup/ssh-pubkey`)
      .then(r => r.json())
      .then(j => {
        setPubkeyExists(!!j.exists);
        setKeyPath(j.path || "");
        if (j.public_key) setPubkey(j.public_key);
      })
      .catch(() => setPubkeyExists(false));
  }, []);

  useEffect(() => {
    try { localStorage.setItem("setup.sshTargets", JSON.stringify(targets.map(t => ({ ...t, result: undefined, testing: undefined })))); } catch {}
  }, [targets]);

  const generate = async (overwrite = false) => {
    setGenerating(true);
    try {
      const r = await fetch(`${API_BASE}/setup/ssh-keygen`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ comment, overwrite }),
      });
      const j = await r.json();
      if (j.public_key) {
        setPubkey(j.public_key);
        setPubkeyExists(true);
        setKeyPath(j.path);
        toast.success(j.created ? "SSH-Key erzeugt" : "SSH-Key existiert bereits");
      } else {
        toast.error(j.error || "Fehler beim Erzeugen");
      }
    } catch (e: any) {
      toast.error(e.message || "Netzwerkfehler – läuft die API?");
    } finally {
      setGenerating(false);
    }
  };

  const copyKey = () => {
    navigator.clipboard.writeText(pubkey);
    toast.success("Public Key kopiert");
  };

  const testTarget = async (id: string) => {
    setTargets(ts => ts.map(t => t.id === id ? { ...t, testing: true, result: undefined } : t));
    const t = targets.find(x => x.id === id)!;
    try {
      const r = await fetch(`${API_BASE}/setup/ssh-test`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ host: t.host, user: t.user, port: t.port }),
      });
      const j = await r.json();
      setTargets(ts => ts.map(x => x.id === id ? { ...x, testing: false, result: j } : x));
    } catch (e: any) {
      setTargets(ts => ts.map(x => x.id === id ? { ...x, testing: false, result: { ok: false, error: e.message } } : x));
    }
  };

  const updateTarget = (id: string, patch: Partial<SshTarget>) =>
    setTargets(ts => ts.map(t => t.id === id ? { ...t, ...patch, result: undefined } : t));

  const addTarget = () =>
    setTargets(ts => [...ts, { id: `t${Date.now()}`, label: "Neues Ziel", host: "", user: "root", port: 22 }]);

  const removeTarget = (id: string) =>
    setTargets(ts => ts.filter(t => t.id !== id));

  return (
    <div className="space-y-5">
      <div className="rounded-md border border-border bg-background p-4 space-y-3">
        <div className="flex items-center justify-between gap-2">
          <h3 className="text-sm font-medium flex items-center gap-2">
            <KeyRound className="h-4 w-4 text-primary" /> Dashboard SSH-Key
          </h3>
          {pubkeyExists === true && <span className="text-xs text-green-500 font-mono">vorhanden</span>}
          {pubkeyExists === false && <span className="text-xs text-muted-foreground font-mono">noch nicht erzeugt</span>}
        </div>
        <p className="text-xs text-muted-foreground">
          Wird im API-Container unter <code className="rounded bg-muted px-1 text-[11px]">{keyPath || "/home/node/.ssh/id_ed25519_dashboard"}</code> abgelegt
          (persistentes Volume <code className="rounded bg-muted px-1 text-[11px]">api_ssh</code>).
        </p>

        {!pubkeyExists && (
          <div className="flex flex-wrap items-end gap-2">
            <div className="flex-1 min-w-[200px] space-y-1">
              <Label className="text-xs">Key-Kommentar</Label>
              <Input value={comment} onChange={e => setComment(e.target.value)} className="h-8 text-xs" />
            </div>
            <Button onClick={() => generate(false)} disabled={generating} size="sm" className="gap-2">
              {generating ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <KeyRound className="h-3.5 w-3.5" />}
              ED25519-Keypair erzeugen
            </Button>
          </div>
        )}

        {pubkey && (
          <>
            <div className="rounded border border-border/50 bg-card p-2 font-mono text-[11px] break-all">
              {pubkey}
            </div>
            <div className="flex flex-wrap gap-2">
              <Button onClick={copyKey} size="sm" variant="outline" className="gap-1.5">
                <Copy className="h-3.5 w-3.5" /> Public Key kopieren
              </Button>
              <Button onClick={() => generate(true)} size="sm" variant="ghost" disabled={generating} className="gap-1.5 text-destructive">
                {generating && <Loader2 className="h-3.5 w-3.5 animate-spin" />} Neu erzeugen (überschreiben)
              </Button>
            </div>
            <details className="text-xs text-muted-foreground">
              <summary className="cursor-pointer hover:text-foreground">Anleitung: Public Key auf Ziel-Host installieren</summary>
              <div className="mt-2 space-y-2 pl-2 border-l-2 border-border">
                <div>
                  <strong className="text-foreground">Linux (ssh-copy-id):</strong>
                  <pre className="mt-1 rounded bg-muted/60 p-2 font-mono text-[10px] overflow-x-auto">echo '{pubkey.split(" ").slice(0,2).join(" ")}...' | ssh root@HOST "mkdir -p ~/.ssh && cat &gt;&gt; ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys"</pre>
                </div>
                <div>
                  <strong className="text-foreground">OPNsense:</strong> System → Access → Users → root → "authorized SSH keys" → Public Key einfügen.
                </div>
                <div>
                  <strong className="text-foreground">Mailcow Host:</strong> normalen User-Account, Public Key in <code>~/.ssh/authorized_keys</code>. Empfohlen: dedizierter User <code>logread</code> mit nur-lese-Sudo für <code>/var/log</code>.
                </div>
              </div>
            </details>
          </>
        )}
      </div>

      <Separator />

      <div className="space-y-3">
        <div className="flex items-center justify-between">
          <h3 className="text-sm font-medium">SSH-Verbindungen testen</h3>
          <Button onClick={addTarget} size="sm" variant="outline" className="gap-1.5 h-7 text-xs">
            <Plus className="h-3 w-3" /> Ziel hinzufügen
          </Button>
        </div>

        {targets.map(t => (
          <div key={t.id} className="rounded-md border border-border bg-background p-3 space-y-2">
            <div className="grid gap-2 sm:grid-cols-12">
              <Input className="sm:col-span-3 h-8 text-xs" value={t.label} onChange={e => updateTarget(t.id, { label: e.target.value })} placeholder="Label" />
              <Input className="sm:col-span-4 h-8 text-xs font-mono" value={t.host} onChange={e => updateTarget(t.id, { host: e.target.value })} placeholder="host.example.com" />
              <Input className="sm:col-span-2 h-8 text-xs font-mono" value={t.user} onChange={e => updateTarget(t.id, { user: e.target.value })} placeholder="user" />
              <Input className="sm:col-span-1 h-8 text-xs font-mono" type="number" value={t.port} onChange={e => updateTarget(t.id, { port: parseInt(e.target.value) || 22 })} />
              <div className="sm:col-span-2 flex gap-1">
                <Button size="sm" className="flex-1 h-8 text-xs gap-1" disabled={!t.host || t.testing || !pubkeyExists} onClick={() => testTarget(t.id)}>
                  {t.testing ? <Loader2 className="h-3 w-3 animate-spin" /> : "Test"}
                </Button>
                <Button size="sm" variant="ghost" className="h-8 w-8 p-0 text-destructive" onClick={() => removeTarget(t.id)}>
                  <Trash2 className="h-3 w-3" />
                </Button>
              </div>
            </div>
            {t.result && (
              <div className={`rounded border px-2 py-1.5 text-[11px] font-mono whitespace-pre-wrap break-all ${
                t.result.ok ? "border-green-500/40 bg-green-500/5 text-green-600" : "border-destructive/40 bg-destructive/5 text-destructive"
              }`}>
                {t.result.ok
                  ? `✓ verbunden (${t.result.latency_ms}ms): ${t.result.stdout || "ok"}`
                  : `✗ ${t.result.error || t.result.stderr || "Fehler"}${t.result.hint ? `\n→ ${t.result.hint}` : ""}`}
              </div>
            )}
          </div>
        ))}

        {!pubkeyExists && (
          <p className="text-xs text-muted-foreground">
            Erst SSH-Key erzeugen, dann sind die Tests aktiv.
          </p>
        )}
      </div>

      <div className="rounded-md border border-border/50 bg-muted/30 p-3 text-xs text-muted-foreground space-y-1">
        <p><strong className="text-foreground">Empfohlene Rechte auf dem Zielsystem:</strong></p>
        <ul className="list-disc pl-4 space-y-0.5">
          <li>Eigener User <code>logread</code> (kein Login-Shell nötig: <code>/usr/sbin/nologin</code> ist ok für Datei-Reads via <code>scp</code>).</li>
          <li>Lesezugriff auf <code>/var/log</code> via Gruppe <code>adm</code>: <code>usermod -aG adm logread</code></li>
          <li>Optional eingeschränktes <code>sudo</code> (nur lesen): <code>logread ALL=(root) NOPASSWD: /usr/bin/tail, /usr/bin/cat, /bin/journalctl</code></li>
        </ul>
      </div>
    </div>
  );
}
