import { useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import {
  ArrowRight,
  ArrowLeft,
  Database,
  HardDrive,
  ShieldCheck,
  Server,
  KeyRound,
  Download,
  Check,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Separator } from "@/components/ui/separator";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";

interface WizardState {
  // Server users
  logUser: string;
  dbUser: string;
  dbPassword: string;
  adminEmail: string;
  // Storage / backup
  backupPath: string;
  backupCron: string;
  // Web
  hostname: string;
  serverIp: string;
  enableHttps: boolean;
  certPath: string;
  // Authentik / SSO
  authentikUrl: string;
  authentikRealm: string;
  oidcClientId: string;
  oidcClientSecret: string;
  ssoGoogle: boolean;
  ssoMicrosoft: boolean;
  ssoSaml: boolean;
  ssoOidc: boolean;
  ssoPassword: boolean;
  authRequired: boolean;
}

const DEFAULT_STATE: WizardState = {
  logUser: "logsrv",
  dbUser: "dashboard",
  dbPassword: "",
  adminEmail: "",
  backupPath: "/var/backups/dashboard",
  backupCron: "0 3 * * *",
  hostname: "dashboard.local",
  serverIp: "0.0.0.0",
  enableHttps: true,
  certPath: "./certs",
  authentikUrl: "https://auth.dashboard.local",
  authentikRealm: "dashboard",
  oidcClientId: "dashboard",
  oidcClientSecret: "",
  ssoGoogle: true,
  ssoMicrosoft: true,
  ssoSaml: true,
  ssoOidc: true,
  ssoPassword: true,
  authRequired: true,
};

const STEPS = [
  { id: "users", label: "User", icon: Server },
  { id: "db", label: "Datenbank", icon: Database },
  { id: "backup", label: "Backup & Cron", icon: HardDrive },
  { id: "web", label: "Web / TLS", icon: ShieldCheck },
  { id: "sso", label: "SSO (Authentik)", icon: KeyRound },
  { id: "review", label: "Übersicht", icon: Check },
] as const;

function buildEnvFile(s: WizardState): string {
  const issuer = `${s.authentikUrl.replace(/\/$/, "")}/application/o/${s.oidcClientId}/`;
  return `# Generated by Dashboard Setup Wizard
# --- Server users ---
LOG_SRV_USER=${s.logUser}
DB_USER=${s.dbUser}
DB_PASSWORD=${s.dbPassword}
ADMIN_EMAIL=${s.adminEmail}

# --- Backup ---
BACKUP_PATH=${s.backupPath}
BACKUP_CRON=${s.backupCron}

# --- Web ---
SERVER_IP=${s.serverIp}
HOSTNAME=${s.hostname}
ENABLE_HTTPS=${s.enableHttps}
CERT_PATH=${s.certPath}

# --- SSO / Authentik ---
AUTHENTIK_URL=${s.authentikUrl}
AUTHENTIK_REALM=${s.authentikRealm}
OIDC_CLIENT_ID=${s.oidcClientId}
OIDC_CLIENT_SECRET=${s.oidcClientSecret}

# --- Frontend (Vite) ---
VITE_AUTH_REQUIRED=${s.authRequired}
VITE_OIDC_AUTHORITY=${issuer}
VITE_OIDC_CLIENT_ID=${s.oidcClientId}
VITE_OIDC_REDIRECT_URI=${s.enableHttps ? "https" : "http"}://${s.hostname}/auth/callback
VITE_OIDC_POST_LOGOUT_URI=${s.enableHttps ? "https" : "http"}://${s.hostname}/login
VITE_SSO_GOOGLE_ENABLED=${s.ssoGoogle}
VITE_SSO_MICROSOFT_ENABLED=${s.ssoMicrosoft}
VITE_SSO_SAML_ENABLED=${s.ssoSaml}
VITE_SSO_OIDC_ENABLED=${s.ssoOidc}
VITE_SSO_PASSWORD_ENABLED=${s.ssoPassword}
`;
}

export default function SetupWizard() {
  const navigate = useNavigate();
  const [step, setStep] = useState(0);
  const [state, setState] = useState<WizardState>(DEFAULT_STATE);

  const update = <K extends keyof WizardState>(key: K, value: WizardState[K]) =>
    setState((s) => ({ ...s, [key]: value }));

  const envFile = useMemo(() => buildEnvFile(state), [state]);

  const downloadEnv = () => {
    const blob = new Blob([envFile], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = ".env";
    a.click();
    URL.revokeObjectURL(url);
    toast.success(".env heruntergeladen");
  };

  const next = () => setStep((s) => Math.min(STEPS.length - 1, s + 1));
  const prev = () => setStep((s) => Math.max(0, s - 1));

  const Current = STEPS[step];

  return (
    <div className="mx-auto max-w-4xl space-y-6 p-4 md:p-8">
      <header className="space-y-2">
        <h1 className="text-2xl font-semibold tracking-tight">Setup-Wizard</h1>
        <p className="text-sm text-muted-foreground">
          Erzeugt eine <code className="rounded bg-muted px-1">.env</code> für das
          Docker-Setup (Debian 12/13 oder Windows Docker Desktop). Die Werte
          werden von <code className="rounded bg-muted px-1">install.sh</code>
          und <code className="rounded bg-muted px-1">docker-compose.yml</code>
          gelesen.
        </p>
      </header>

      {/* Stepper */}
      <ol className="flex flex-wrap items-center gap-2 text-sm">
        {STEPS.map((s, i) => {
          const Icon = s.icon;
          const active = i === step;
          const done = i < step;
          return (
            <li key={s.id} className="flex items-center gap-2">
              <button
                onClick={() => setStep(i)}
                className={`flex items-center gap-2 rounded-full border px-3 py-1.5 transition ${
                  active
                    ? "border-primary bg-primary text-primary-foreground"
                    : done
                    ? "border-primary/40 bg-primary/10 text-primary"
                    : "border-border bg-card text-muted-foreground"
                }`}
              >
                <Icon className="h-3.5 w-3.5" />
                {s.label}
              </button>
              {i < STEPS.length - 1 && <ArrowRight className="h-3 w-3 text-muted-foreground" />}
            </li>
          );
        })}
      </ol>

      <section className="rounded-2xl border border-border bg-card p-6 shadow-sm">
        <h2 className="mb-4 flex items-center gap-2 text-lg font-medium">
          <Current.icon className="h-5 w-5 text-primary" />
          {Current.label}
        </h2>

        {Current.id === "users" && (
          <div className="grid gap-4 md:grid-cols-2">
            <Field label="Log-Server User (Linux)" value={state.logUser} onChange={(v) => update("logUser", v)} hint="System-User unter dem der Log-Collector läuft" />
            <Field label="Admin Email" value={state.adminEmail} onChange={(v) => update("adminEmail", v)} hint="Initialer Dashboard-Admin (wird in Authentik angelegt)" />
          </div>
        )}

        {Current.id === "db" && (
          <div className="grid gap-4 md:grid-cols-2">
            <Field label="Datenbank-User" value={state.dbUser} onChange={(v) => update("dbUser", v)} />
            <Field label="Datenbank-Passwort" value={state.dbPassword} onChange={(v) => update("dbPassword", v)} type="password" hint="Wird in das Postgres-Image als POSTGRES_PASSWORD übergeben" />
          </div>
        )}

        {Current.id === "backup" && (
          <div className="grid gap-4 md:grid-cols-2">
            <Field label="Backup-Verzeichnis" value={state.backupPath} onChange={(v) => update("backupPath", v)} hint="Volume für DB-Dumps und Log-Snapshots" />
            <Field label="Cron-Schedule" value={state.backupCron} onChange={(v) => update("backupCron", v)} hint="Standard 03:00 Uhr täglich" />
            <p className="md:col-span-2 text-xs text-muted-foreground">
              <code>install.sh</code> legt einen Cron-Eintrag im Backup-Container
              an, der täglich <code>pg_dump</code> + <code>tar</code> der Logs
              ausführt.
            </p>
          </div>
        )}

        {Current.id === "web" && (
          <div className="grid gap-4 md:grid-cols-2">
            <Field label="Hostname" value={state.hostname} onChange={(v) => update("hostname", v)} hint="z.B. dashboard.example.com" />
            <Toggle label="HTTPS aktivieren" checked={state.enableHttps} onChange={(v) => update("enableHttps", v)} hint="HTTP bleibt parallel auf Port 80 verfügbar" />
            <Field label="Zertifikats-Verzeichnis" value={state.certPath} onChange={(v) => update("certPath", v)} hint="Lege hier deine Let's-Encrypt fullchain.pem + privkey.pem ab" />
          </div>
        )}

        {Current.id === "sso" && (
          <div className="grid gap-4 md:grid-cols-2">
            <Field label="Authentik URL" value={state.authentikUrl} onChange={(v) => update("authentikUrl", v)} hint="Basis-URL des Authentik-Servers" />
            <Field label="Authentik Realm / Slug" value={state.authentikRealm} onChange={(v) => update("authentikRealm", v)} />
            <Field label="OIDC Client-ID" value={state.oidcClientId} onChange={(v) => update("oidcClientId", v)} />
            <Field label="OIDC Client-Secret" value={state.oidcClientSecret} onChange={(v) => update("oidcClientSecret", v)} type="password" hint="Aus Authentik → Provider → Dashboard kopieren" />

            <div className="md:col-span-2 mt-2 space-y-3">
              <Separator />
              <h3 className="text-sm font-medium">Aktive Login-Methoden</h3>
              <div className="grid gap-3 sm:grid-cols-2">
                <Toggle label="Google" checked={state.ssoGoogle} onChange={(v) => update("ssoGoogle", v)} />
                <Toggle label="Microsoft / Entra" checked={state.ssoMicrosoft} onChange={(v) => update("ssoMicrosoft", v)} />
                <Toggle label="SAML SSO" checked={state.ssoSaml} onChange={(v) => update("ssoSaml", v)} />
                <Toggle label="Generic OIDC" checked={state.ssoOidc} onChange={(v) => update("ssoOidc", v)} />
                <Toggle label="Email + Passwort" checked={state.ssoPassword} onChange={(v) => update("ssoPassword", v)} />
                <Toggle label="Auth-Wall erzwingen" checked={state.authRequired} onChange={(v) => update("authRequired", v)} hint="Login zwingend, sonst freier Zugriff" />
              </div>
              <p className="text-xs text-muted-foreground">
                Google / Microsoft / SAML werden als <strong>Federated Sources</strong>{" "}
                in Authentik konfiguriert. Die Buttons hier blenden sie nur in
                der Login-UI ein/aus.
              </p>
            </div>
          </div>
        )}

        {Current.id === "review" && (
          <div className="space-y-4">
            <p className="text-sm text-muted-foreground">
              Lade die generierte <code>.env</code> herunter, lege sie neben
              <code> docker-compose.yml</code> und führe <code>./install.sh</code>{" "}
              aus (Linux) bzw. <code>docker compose up -d</code> (Windows).
            </p>
            <Textarea readOnly value={envFile} className="h-72 font-mono text-xs" />
            <div className="flex gap-2">
              <Button onClick={downloadEnv} className="gap-2">
                <Download className="h-4 w-4" /> .env herunterladen
              </Button>
              <Button variant="outline" onClick={() => navigate("/")}>Zum Dashboard</Button>
            </div>
          </div>
        )}
      </section>

      <div className="flex justify-between">
        <Button variant="outline" onClick={prev} disabled={step === 0} className="gap-2">
          <ArrowLeft className="h-4 w-4" /> Zurück
        </Button>
        <Button onClick={next} disabled={step === STEPS.length - 1} className="gap-2">
          Weiter <ArrowRight className="h-4 w-4" />
        </Button>
      </div>
    </div>
  );
}

function Field({
  label,
  value,
  onChange,
  hint,
  type = "text",
}: {
  label: string;
  value: string;
  onChange: (v: string) => void;
  hint?: string;
  type?: string;
}) {
  return (
    <div className="space-y-1">
      <Label>{label}</Label>
      <Input type={type} value={value} onChange={(e) => onChange(e.target.value)} />
      {hint && <p className="text-xs text-muted-foreground">{hint}</p>}
    </div>
  );
}

function Toggle({
  label,
  checked,
  onChange,
  hint,
}: {
  label: string;
  checked: boolean;
  onChange: (v: boolean) => void;
  hint?: string;
}) {
  return (
    <div className="flex items-start gap-3 rounded-md border border-border bg-background p-3">
      <Switch checked={checked} onCheckedChange={onChange} />
      <div className="space-y-0.5">
        <Label className="cursor-pointer">{label}</Label>
        {hint && <p className="text-xs text-muted-foreground">{hint}</p>}
      </div>
    </div>
  );
}
